server:
  port: ${API_SERVER_PORT:8080}
spring:
  application:
    name: clinic-center-api
  datasource:
    username: ${API_DB_USERNAME:sonar}
    password: ${API_DB_PASSWORD:sonar}
    url: jdbc:postgresql://${API_DB_SERVER_URL:localhost}:${API_DB_SERVER_PORT:5432}/clinic
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: resource-server
          client-secret: checkToken123
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
  file:
    name: boot_api.log
